---
- name: Search Graylog prometheus exporter user if exists
  uri:
    url: '{% if graylog_https | bool %}https{% else %}http{% endif %}://{{ ansible_default_ipv4.address }}:{{ graylog_port_arg.api }}/api/users/prometheus'
    method: 'GET'
    user: '{{ graylog_root_user }}'
    password: '{{ graylog_root_pass }}'
    force_basic_auth: 'yes'
    status_code: '200'
    validate_certs: 'no'
    headers:
      X-Requested-By: '{{ ansible_default_ipv4.address }}'
      cache-control: 'no-cache'
  environment:
    no_proxy: '{{ ansible_default_ipv4.address }}'
  changed_when: false
  failed_when: false
  register: graylog_exporter_user

- name: Create Graylog prometheus exporter user
  uri:
    url: '{% if graylog_https | bool %}https{% else %}http{% endif %}://{{ ansible_default_ipv4.address }}:{{ graylog_port_arg.api }}/api/users'
    method: 'POST'
    user: '{{ graylog_root_user }}'
    password: '{{ graylog_root_pass }}'
    body: '{"username":"prometheus","password":"password","email":"prometheus@domain.com","full_name":"prometheus","permissions":["users:edit:prometheus","users:tokencreate:prometheus","users:tokenlist:prometheus","users:tokenremove:prometheus","users:passwordchange:prometheus","clusterconfigentry:read","indexercluster:read","messagecount:read","journal:read","messages:analyze","inputs:read","metrics:read","savedsearches:edit","fieldnames:read","buffers:read","system:read","savedsearches:create","jvmstats:read","decorators:read","throughput:read","savedsearches:read","messages:read"],"timezone":"Asia/Shanghai","session_timeout_ms":3600000,"startpage":null,"roles":["Reader"]}'
    force_basic_auth: 'yes'
    status_code: '201'
    validate_certs: 'no'
    body_format: 'json'
    headers:
      X-Requested-By: '{{ ansible_default_ipv4.address }}'
      cache-control: 'no-cache'
  environment:
    no_proxy: '{{ ansible_default_ipv4.address }}'
  register: register_status
  until: register_status.status == 201
  retries: 10
  delay: 3
  when:
    - graylog_exporter_user.status == 404

- name: Create Graylog prometheus exporter user token
  uri:
    url: '{% if graylog_https | bool %}https{% else %}http{% endif %}://{{ ansible_default_ipv4.address }}:{{ graylog_port_arg.api }}/api/users/prometheus/tokens/default'
    method: 'POST'
    user: '{{ graylog_root_user }}'
    password: '{{ graylog_root_pass }}'
    force_basic_auth: 'yes'
    status_code: '200'
    validate_certs: 'no'
    headers:
      X-Requested-By: '{{ ansible_default_ipv4.address }}'
      cache-control: 'no-cache'
  environment:
    no_proxy: '{{ ansible_default_ipv4.address }}'
  register: register_status
  until: register_status.status == 200
  retries: 10
  delay: 3
  no_log: true
  when:
    - graylog_exporter_user.status == 404
