---
- name: Gathering service facts
  service_facts:
  register: services_state

- name: Allow Graylog service port
  firewalld:
    port: '{{ item.value }}/tcp'
    zone: 'public'
    permanent: 'true'
    immediate: 'true'
    state: 'enabled'
  loop: '{{ graylog_port_arg|dict2items }}'
  when: services_state.ansible_facts.services["firewalld.service"].state == 'running'

- name: Allow Graylog inputs port
  firewalld:
    port: "{{ item.port }}/{{ item.name.split(' ')[1] | lower }}"
    zone: 'public'
    permanent: 'true'
    immediate: 'true'
    state: 'enabled'
  loop: '{{ graylog_inputs_arg }}'
  when:
    - graylog_inputs_arg is defined
    - services_state.ansible_facts.services["firewalld.service"].state == 'running'

- name: Allow Graylog Content Packs inputs port
  firewalld:
    port: "{{ item.port }}/{{ item.protocol | lower }}"
    zone: 'public'
    permanent: 'true'
    immediate: 'true'
    state: 'enabled'
  loop: '{{ graylog_content_packs_arg }}'
  when:
    - graylog_content_packs_arg is defined
    - services_state.ansible_facts.services["firewalld.service"].state == 'running'