---
- name: Include OS-specific variables
  include_vars: '{{ ansible_os_family }}.yml'

- name: Add Graylog YUM repositories
  yum_repository:
    name: '{{ graylog_repo_name }}'
    description: '{{ graylog_repo_name }} YUM repository'
    file: '{{ graylog_repo_name }}'
    baseurl: '{{ graylog_repo_url }}'
    gpgcheck: 'no'
    timeout: '60'

- name: Install the Graylog packages
  yum:
    name: '{{ item }}'
    state: 'present'
    validate_certs: 'no'
    disable_gpg_check: 'yes'
  loop: '{{ dependent_packages|flatten(levels=1) }}'
  register: yum_status
  until: yum_status is succeeded
  retries: 3
  delay: 5
